### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by bminer** [soifou/sublime-shfmt#1]
Install works, but it does not use shfmt to format the file

**Comment by shenzhigang** [comment]
sublime 4 not supported?

**Comment by soifou** [comment]
I don't use sublime text anymore but I can try to troubleshoot you. I just tried on a fresh sublime text 4 and it still works fine. What kind of error do you have ? Is `shfmt` binary available in your PATH ? 

This should work on linux but no guarantee that works on windows or mac.

**Comment by bminer** [comment]
Yeah it appears that it cannot find `shfmt` even though it's in my `PATH`.

```
Package Control: Installed package "sublime-shfmt" 2024.02.02.18.54.44
ignored packages updated to: ["Vintage"]
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading python 3.3 plugin sublime-shfmt.shfmt
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1499, in run_
    return self.run(edit)
  File "/home/blake/.config/sublime-text-3/Packages/sublime-shfmt/shfmt.py", line 110, in run
    format_code(edit, self.view, region)
  File "/home/blake/.config/sublime-text-3/Packages/sublime-shfmt/shfmt.py", line 29, in format_code
    stderr=subprocess.PIPE,
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1452, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'shfmt'
```

shfmt is in my `PATH`.

```bash
$ which shfmt
/home/blake/go/bin/shfmt
$ echo $PATH
/home/blake/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/blake/go/bin
```

I also tried editing `shfmt.sublime-settings`:

```json
{
    "config": {
        // Turns on autoformatting on save
        "autoformat": true,
    },
    "paths": {
        "linux": "~/go/bin",
        "osx": "",
        "windows": ""
    },
}
```

After saving the settings file, I still get:

```
reloading settings Packages/User/shfmt.sublime-settings
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python33/sublime_plugin.py", line 1499, in run_
    return self.run(edit)
  File "/home/blake/.config/sublime-text-3/Packages/sublime-shfmt/shfmt.py", line 110, in run
    format_code(edit, self.view, region)
  File "/home/blake/.config/sublime-text-3/Packages/sublime-shfmt/shfmt.py", line 29, in format_code
    stderr=subprocess.PIPE,
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1452, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'shfmt'
```

Any suggestions?

**Comment by bminer** [comment]
I am pretty sure the issue here is that `subprocess.Popen` wants a fully qualified path to the executable. There is a warning in the Python docs:

> Warning
> 
> For maximum reliability, use a fully qualified path for the executable. To search for an unqualified name on PATH, use [shutil.which()](https://docs.python.org/3/library/shutil.html#shutil.which). On all platforms, passing [sys.executable](https://docs.python.org/3/library/sys.html#sys.executable) is the recommended way to launch the current Python interpreter again, and use the -m command-line format to launch an installed module.
>
> Resolving the path of executable (or the first item of args) is platform dependent. For POSIX, see [os.execvpe()](https://docs.python.org/3/library/os.html#os.execvpe), and note that when resolving or searching for the executable path, cwd overrides the current working directory and env can override the PATH environment variable. For Windows, see the documentation of the lpApplicationName and lpCommandLine parameters of WinAPI CreateProcess, and note that when resolving or searching for the executable path with shell=False, cwd does not override the current working directory and env cannot override the PATH environment variable. Using a full path avoids all of these variations.

**Comment by soifou** [comment]
Thank you for the insight, could you try the latest version and tell me if it is now correctly detected?

**Comment by bminer** [comment]
It is not (and now I get dialog popup).

I see the problem, though. I am adding `shfmt` to the `PATH` in my .bashrc file.

So, when I manually add the path to the sublime-settings config, it might just work. I submitted a PR #2 to address these issues. Let me know what you think!
