### ISSUE TITLE
Make scopes configurable

### ISSUE THREAD

**Issue by bminer** [soifou/sublime-shfmt#3]
It would be nice if the plugin's `autoformat` on-save function could use a customizable list of scope names.

Currently, it looks for a scope starting with "source.shell", but it would be nice if some scopes could be blacklisted or whitelisted. I'm happy to open a PR for this. Thoughts?

My use case is that sublime-shfmt is now formatting my Nushell scripts on save, and their scope is "source.shell.nu". I don't want this to happen.

**Comment by soifou** [comment]
Make sense! Yes please open a PR :)
